### PR TITLE
 Update modDesc_l10n_fr.xml

### PR DESCRIPTION
**Pull request by Anonymous-any**
v1.0.3.27

### CODE REVIEW

**Comment by DeckerMMIV** [comment]
Regarding your comment: "seem never showed event if a key is added to input_VEGS_GRP_NXT. Maybe need fine tune if it should function"

Those two input-bindings should appear in the 'F1 helpbox' only when the VEGS-modifier-key is pressed - (default LEFT CTRL).
fsscreen_2017_07_26_17_11_16-b
_Note: Some character/letter symbols is not available in FS17's font-bitmap, so only a "blank square" is shown. - I've mapped 'switch to next group' to my Ø key._

**Comment by Anonymous-any** [comment]
Well maybe I found my issue why that don't show can you confirm I maybe have too more things which must be displayed at the same time, it seem also display by some priority between them? The first thing that makes me think that is your screen is not long list in comparison to mine (I have lots, lots mods i'm silly if I did not think to load only the minimum) idk, event I press only Left-ctrl that seem sometime change nothing have a look but don't care anymore if other ppl have no report that.. I have too VEGS_GRP_TAB key to BUTTON_8 but that never display the message function of course that switch work :). I was just a translator who try to show all options for good and/or precise/best translation ;) on the screen 3 are in edit mode 1 only in normal mode and I been think too VEGS_GRP_NXT and VEGS_GRP_TAB are only show when in normal mode and you go say me :) that why I ask the more details if you see something wrong to me:

Best regard

**Comment by DeckerMMIV** [comment]
Ah yes, the problem that the F1-helpbox only shows a maximum of 8 elements. - I actually made a mod for myself, which turn specific action-texts into very-low-priority elements, so they will appear further down in the F1-helpbox list, or will be completely hidden _(I don't need to be reminded that 'E' enters/leaves vehicle or other frequently used actions like that.)_

So that is most likely why you can't see the VeGS 'to next group' and 'switch within group', as they have a low-priority (GS_PRIO_LOW):
```
-- Show keys in helpbox, only when modifier-key is pressed (if it has been assigned)
g_currentMission:addHelpButtonText(g_i18n:getText("VEGS_GRP_TAB"), InputBinding.VEGS_GRP_TAB ,nil ,GS_PRIO_LOW);
g_currentMission:addHelpButtonText(g_i18n:getText("VEGS_GRP_NXT"), InputBinding.VEGS_GRP_NXT ,nil ,GS_PRIO_LOW);
``` 
I do not, at the moment, have any suggestions for you on how to make those low-priority action-texts visible in the F1-helpbox - other than attempting to only have this one mod as the only mod selected, then try to see if there is a vehicle (maybe the Pickup car?) with very few normal actions.

**Comment by Anonymous-any** [comment]
(I don't need to be reminded that 'E' enters/leaves vehicle or other frequently used actions like that.) sure you right ! a good mods option will be a bit same like glance for F1 menu :) where it could make show tweaked and some set already installed options and mostly more than 8 elements if possible in this stupid menu :/ all versions of Farming have always been bored with this... thank Maestro

Ps: I do not, at the moment, have any suggestions for you on how to make those low-priority action-texts visible in the F1-helpbox ->don't care about that you are not going to re-write the full game ^^

**Pull request merged**
